GET http://localhost:3000/tags

POST http://localhost:3000/tags
Content-Type: application/json
{
    "name":"javascript",
    "slug" : "js javascript",
    "description" : "javascript is dynamic programming language used to created interactive websites",
    "featuredImageUrl": "www.js.com"
}
