GET http://localhost:3000/posts/

POST http://localhost:3000/posts
Content-Type: application/json
{
    "title":"with author id",
    "postType" : "post",
    "slug" : "abc",
    "status": "draft",
    "content":"lorem ipusm lid kdif di fidi",
    "featuredImageUrl":"image link here",
    "publishedAt":"2021-09-09T00:00:00.000Z",
    "seo": {
        "metaTitle":"sameer",
        "metaDescription":"sameer",
        "metaKeywords":"sameer"
    },
    "authorId":1
    // "tags":["sameer"]
}

DELETE http://localhost:3000/posts/?id=2

PATCH http://localhost:3000/posts
Content-Type: application/json
{
    "tags":["sameer"]
}