# GET http://localhost:3000/users/1/?page=1&limit=10
GET http://localhost:3000/users

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname":"sameer",
    "lastname":"sha",
    "email":"hms@gmail.com",
    "password":"Sameer@62"
    // "isAuth":true
}

PATCH http://localhost:3000/users
Content-Type: application/json

{
    "firstname":"WAH WAH",
}