GET http://localhost:3000/users

GET http://localhost:3000/users/2

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname":"sameer",
    "lastname":"sha",
    "email":"hms2@gmail.com",
    "password":"Sameer@6251"
    // "isAuth":true
}


POST http://localhost:3000/users/create-many
Content-Type: application/json
{
    "users":[
        {
            "firstname":"tom",
            "lastname":"cat",
            "email":"tom@gmail.com",
            "password":"Sameer@62"
         }, 
         {
            "firstname":"jackiechan",
            "lastname":"chan",
            "email":"hmss@gmail.com",
            "password":"Sameer@62"
         }
    ]
}


PATCH http://localhost:3000/users
Content-Type: application/json

{
    "firstname":"WAH WAH",
}